In [7]:
import numpy as np

In [16]:
n1=np.array([1,2,3,4])

In [42]:
np.zeros((1,2))


array([[0., 0.]])

In [12]:
n1

array([[0., 0.]])

In [13]:
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [14]:
n1=np.arange(1,10)
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
n1=np.arange(1,10,2)
n1

array([1, 3, 5, 7, 9])

In [21]:
n1=np.random.randint(100,200,10)
n1

array([138, 122, 140, 115, 142, 132, 160, 139, 199, 198])

In [27]:
n1.shape=(3,2)
n1

array([[1, 2],
       [3, 5],
       [6, 7]])

In [24]:
n1=np.array([[1,2,3],[5,6,7]])
n1.shape

(2, 3)

In [34]:
n1=np.array([10,30])
n2=np.array([20,30])
np.vstack((n1,n2))

array([[10, 30],
       [20, 30]])